language: php

matrix:
  include:
    - dist: bionic
      php: 7.2
    - dist: bionic
      php: 7.3
    - dist: bionic
      php: 7.4

install: travis_retry composer install

script: vendor/bin/phpunit
